### ISSUE TITLE
Add ability to get bank identifier and account number from BBAN

### ISSUE THREAD

**Issue by svenstaro** [ThomasdenH/iban_validate#17]
Hi, nice crate! I'm currently using it to make a project.

However, I'm currently at a point where it would be super convenient to get the bank identifier and account number (and for some countries the bank branch identifier) directly from the BBAN. See [here](https://www.xe.com/ibancalculator/) for reference. That would be a super sweet feature to have!

**Comment by ThomasdenH** [comment]
Sounds like a great extension. This is all detailed in the [SWIFT IBAN registry](https://www.swift.com/standards/data-standards/iban). I am not sure I have the time to do this soon, but I'll definitely accept a PR for this!

**Comment by ThomasdenH** [comment]
I have added the bank and branch identifier. The account number is not as straightforward, as it is not defined in the spec, and the remaining part of the IBAN is not always a consecutive string. For that reason I'm not sure whether it would be a good addition.

**Comment by svenstaro** [comment]
Ok cool, thanks. I'll check it out.
