### ISSUE TITLE
bank_identifier should either not panic or not be an Option

### ISSUE THREAD

**Issue by svenstaro** [ThomasdenH/iban_validate#25]
Currently, `bank_identifier()` is both an `Option` but it also panics. Therefore, it's useless for it to be an `Option`. I think it'd be preferable to have two methods: one that panics and one that's an `Option` or something along those lines.

**Comment by svenstaro** [comment]
Same logic applies to `branch_identifier`.

**Comment by svenstaro** [comment]
Hm ok actually looking into this further, it's not useless as you also explicitly use `None` in some instances. However, it should still not necessarily panic.

**Comment by ThomasdenH** [comment]
Thank you for your reports! The panic indicates a bug as it only happens when an IBAN has an invalid country code, which shouldn't pass validation. `None` indicates no identifier is available for a known country.
