### ISSUE TITLE
thread 'main' panicked at 'Could not compile regular expression for IBAN addresses. Please file an issue at https://github.com/ThomasdenH/iban_validate

### ISSUE THREAD

**Issue by svenstaro** [ThomasdenH/iban_validate#26]
The problem exists because your crate doesn't enable the `unicode-perl`feature of `regex`. I'm not sure how your tests pass but this should be fixed.

**Comment by svenstaro** [comment]
As a fix, I can just add add

```
[dependencies.regex]
version = "1"
features = ["unicode-perl"]
```

to my `Cargo.toml`. Still would be nice if this just worked.

**Comment by ThomasdenH** [comment]
Hmm, this is indeed strange. Maybe the behaviour is dependent on the version of `regex`. Do you know the exact version you use? Either way, I think the flags `unicode-bool` and `unicode-gencat` should be enough to fix this as well.

**Comment by ThomasdenH** [comment]
I cannot reproduce this issue locally. Can you check if it is fixed for you in the latest master?

**Comment by ThomasdenH** [comment]
The newest version doesn't use regex anymore, which fixes this issue. Please let me know if you have any trouble.
