### ISSUE TITLE
Add IBAN struct, with FromStr impl

### ISSUE THREAD

**Issue by killercup** [ThomasdenH/iban_validate#5]
In addition to validating an IBAN, it makes sense to also store valid IBANs as their own type.

I'd add a `struct Iban { … }` that can only be constructed by calling `Iban::from_str("…")?` (or, `"…".parse()?`, thanks to `std::str::FromStr`), validating the Iban in the process. The `Iban` type could just be a newtype wrapper around `String`, and maybe also have a convenience method to get the country code. Implementing `Deref<Target = str>` will make it work where `&str` is expected.

**Comment by ThomasdenH** [comment]
`Iban::from_str()` should probably replace `validate_iban`, and not `validate_iban_country`, since the latter does not validate the Iban standard itself. `validate_iban_country` could then be a function on the `Iban` struct.
